#!/bin/bash -e

# Do we want to modify the config first with the script?
[ -f /etc/service/postfix/run.config ] && source /etc/service/postfix/run.config

if [ "$MAILNAME" ]; then
  echo "$MAILNAME" > /etc/mailname
  postconf -e myhostname="$MAILNAME"
fi

if [ "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi

if [ "$RELAYHOST" ]; then
  postconf -e relayhost="$RELAYHOST"
fi

if [ "$RELAYUSER" ]; then
  postconf -e smtp_sasl_password_maps="hash:/etc/postfix/relay_password"
  postconf -e smtp_sasl_auth_enable="yes"
  postconf -e smtp_sasl_security_options=""
  echo "$RELAYHOST $RELAYUSER:$RELAYPASS" > /etc/postfix/relay_password
  postmap /etc/postfix/relay_password
fi

# We have to start and stop postfix first through init.d to populate
# postfix spool directory for chroot in which postfix is running.
/etc/init.d/postfix start
/etc/init.d/postfix abort

# Is there any other script to run here?
[ -f /etc/service/postfix/run.initialization ] && source /etc/service/postfix/run.initialization

exec /usr/lib/postfix/master -c /etc/postfix -d 2>&1
